//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNJC.BLL.waterDBLService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="waterDBLService.DataServiceSoap")]
    public interface DataServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataStatisticsTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDataStatisticsTable(string SiteCode, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataStatisticsTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataStatisticsTableAsync(string SiteCode, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataInfoTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDataInfoTable(string SiteCode, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataInfoTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataInfoTableAsync(string SiteCode, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThreeHourDataDBRateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        JNJC.BLL.waterDBLService.T_Temp_DBTJ[] GetThreeHourDataDBRateList(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThreeHourDataDBRateList", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.waterDBLService.T_Temp_DBTJ[]> GetThreeHourDataDBRateListAsync(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThreeDataStatisticsTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetThreeDataStatisticsTable(string SiteCode, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThreeDataStatisticsTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetThreeDataStatisticsTableAsync(string SiteCode, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlarmDataStatisticsTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAlarmDataStatisticsTable(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlarmDataStatisticsTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAlarmDataStatisticsTableAsync(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlarmDataStatisticsTable_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAlarmDataStatisticsTable_S(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlarmDataStatisticsTable_S", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAlarmDataStatisticsTable_SAsync(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRunDataRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        JNJC.BLL.waterDBLService.T_Temp_RunRate[] GetRunDataRate(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRunDataRate", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.waterDBLService.T_Temp_RunRate[]> GetRunDataRateAsync(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        JNJC.BLL.waterDBLService.T_Temp_DBTJ[] GetReportInfo(string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.waterDBLService.T_Temp_DBTJ[]> GetReportInfoAsync(string StartDate, string EndDate);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class T_Temp_DBTJ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string regionNameField;
        
        private string regionCodeField;
        
        private string siteCodeField;
        
        private string siteNameField;
        
        private string zhDblField;
        
        private string gmsyDataField;
        
        private string gmsyDblField;
        
        private string zdDataField;
        
        private string zdDblField;
        
        private string zlDataField;
        
        private string zlDblField;
        
        private string adDataField;
        
        private string adDblField;
        
        private string rjyDataField;
        
        private string rjyDblField;
        
        private string swdxDataField;
        
        private string swdxYjsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RegionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("RegionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegionCode {
            get {
                return this.regionCodeField;
            }
            set {
                this.regionCodeField = value;
                this.RaisePropertyChanged("RegionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SiteCode {
            get {
                return this.siteCodeField;
            }
            set {
                this.siteCodeField = value;
                this.RaisePropertyChanged("SiteCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZhDbl {
            get {
                return this.zhDblField;
            }
            set {
                this.zhDblField = value;
                this.RaisePropertyChanged("ZhDbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string GmsyData {
            get {
                return this.gmsyDataField;
            }
            set {
                this.gmsyDataField = value;
                this.RaisePropertyChanged("GmsyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string GmsyDbl {
            get {
                return this.gmsyDblField;
            }
            set {
                this.gmsyDblField = value;
                this.RaisePropertyChanged("GmsyDbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZdData {
            get {
                return this.zdDataField;
            }
            set {
                this.zdDataField = value;
                this.RaisePropertyChanged("ZdData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZdDbl {
            get {
                return this.zdDblField;
            }
            set {
                this.zdDblField = value;
                this.RaisePropertyChanged("ZdDbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ZlData {
            get {
                return this.zlDataField;
            }
            set {
                this.zlDataField = value;
                this.RaisePropertyChanged("ZlData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZlDbl {
            get {
                return this.zlDblField;
            }
            set {
                this.zlDblField = value;
                this.RaisePropertyChanged("ZlDbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AdData {
            get {
                return this.adDataField;
            }
            set {
                this.adDataField = value;
                this.RaisePropertyChanged("AdData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AdDbl {
            get {
                return this.adDblField;
            }
            set {
                this.adDblField = value;
                this.RaisePropertyChanged("AdDbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RjyData {
            get {
                return this.rjyDataField;
            }
            set {
                this.rjyDataField = value;
                this.RaisePropertyChanged("RjyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RjyDbl {
            get {
                return this.rjyDblField;
            }
            set {
                this.rjyDblField = value;
                this.RaisePropertyChanged("RjyDbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SwdxData {
            get {
                return this.swdxDataField;
            }
            set {
                this.swdxDataField = value;
                this.RaisePropertyChanged("SwdxData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string SwdxYjs {
            get {
                return this.swdxYjsField;
            }
            set {
                this.swdxYjsField = value;
                this.RaisePropertyChanged("SwdxYjs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class T_Temp_RunRate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string reigonCodeField;
        
        private string siteCodeField;
        
        private string regionNameField;
        
        private string siteNameField;
        
        private string runRateField;
        
        private string dataEfficiencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReigonCode {
            get {
                return this.reigonCodeField;
            }
            set {
                this.reigonCodeField = value;
                this.RaisePropertyChanged("ReigonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SiteCode {
            get {
                return this.siteCodeField;
            }
            set {
                this.siteCodeField = value;
                this.RaisePropertyChanged("SiteCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("RegionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RunRate {
            get {
                return this.runRateField;
            }
            set {
                this.runRateField = value;
                this.RaisePropertyChanged("RunRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DataEfficiency {
            get {
                return this.dataEfficiencyField;
            }
            set {
                this.dataEfficiencyField = value;
                this.RaisePropertyChanged("DataEfficiency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : JNJC.BLL.waterDBLService.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<JNJC.BLL.waterDBLService.DataServiceSoap>, JNJC.BLL.waterDBLService.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDataStatisticsTable(string SiteCode, string StartDate, string EndDate) {
            return base.Channel.GetDataStatisticsTable(SiteCode, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataStatisticsTableAsync(string SiteCode, string StartDate, string EndDate) {
            return base.Channel.GetDataStatisticsTableAsync(SiteCode, StartDate, EndDate);
        }
        
        public System.Data.DataTable GetDataInfoTable(string SiteCode, string StartDate, string EndDate) {
            return base.Channel.GetDataInfoTable(SiteCode, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataInfoTableAsync(string SiteCode, string StartDate, string EndDate) {
            return base.Channel.GetDataInfoTableAsync(SiteCode, StartDate, EndDate);
        }
        
        public JNJC.BLL.waterDBLService.T_Temp_DBTJ[] GetThreeHourDataDBRateList(string StartDate, string EndDate) {
            return base.Channel.GetThreeHourDataDBRateList(StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.waterDBLService.T_Temp_DBTJ[]> GetThreeHourDataDBRateListAsync(string StartDate, string EndDate) {
            return base.Channel.GetThreeHourDataDBRateListAsync(StartDate, EndDate);
        }
        
        public System.Data.DataTable GetThreeDataStatisticsTable(string SiteCode, string StartDate, string EndDate) {
            return base.Channel.GetThreeDataStatisticsTable(SiteCode, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetThreeDataStatisticsTableAsync(string SiteCode, string StartDate, string EndDate) {
            return base.Channel.GetThreeDataStatisticsTableAsync(SiteCode, StartDate, EndDate);
        }
        
        public System.Data.DataTable GetAlarmDataStatisticsTable(string StartDate, string EndDate) {
            return base.Channel.GetAlarmDataStatisticsTable(StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAlarmDataStatisticsTableAsync(string StartDate, string EndDate) {
            return base.Channel.GetAlarmDataStatisticsTableAsync(StartDate, EndDate);
        }
        
        public System.Data.DataTable GetAlarmDataStatisticsTable_S(string StartDate, string EndDate) {
            return base.Channel.GetAlarmDataStatisticsTable_S(StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAlarmDataStatisticsTable_SAsync(string StartDate, string EndDate) {
            return base.Channel.GetAlarmDataStatisticsTable_SAsync(StartDate, EndDate);
        }
        
        public JNJC.BLL.waterDBLService.T_Temp_RunRate[] GetRunDataRate(string StartDate, string EndDate) {
            return base.Channel.GetRunDataRate(StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.waterDBLService.T_Temp_RunRate[]> GetRunDataRateAsync(string StartDate, string EndDate) {
            return base.Channel.GetRunDataRateAsync(StartDate, EndDate);
        }
        
        public JNJC.BLL.waterDBLService.T_Temp_DBTJ[] GetReportInfo(string StartDate, string EndDate) {
            return base.Channel.GetReportInfo(StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.waterDBLService.T_Temp_DBTJ[]> GetReportInfoAsync(string StartDate, string EndDate) {
            return base.Channel.GetReportInfoAsync(StartDate, EndDate);
        }
    }
}
