//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNHB.WebService.cityAQIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cityAQIService.AirWebServiceSoap")]
    public interface AirWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HNHB.WebService.cityAQIService.HelloWorldResponse HelloWorld(HNHB.WebService.cityAQIService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.HelloWorldResponse> HelloWorldAsync(HNHB.WebService.cityAQIService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirStationHours", ReplyAction="*")]
        HNHB.WebService.cityAQIService.AirStationHoursResponse AirStationHours(HNHB.WebService.cityAQIService.AirStationHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirStationHours", ReplyAction="*")]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirStationHoursResponse> AirStationHoursAsync(HNHB.WebService.cityAQIService.AirStationHoursRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirWords", ReplyAction="*")]
        HNHB.WebService.cityAQIService.AirWordsResponse AirWords(HNHB.WebService.cityAQIService.AirWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirWords", ReplyAction="*")]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirWordsResponse> AirWordsAsync(HNHB.WebService.cityAQIService.AirWordsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityForecastart", ReplyAction="*")]
        HNHB.WebService.cityAQIService.AirCityForecastartResponse AirCityForecastart(HNHB.WebService.cityAQIService.AirCityForecastartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityForecastart", ReplyAction="*")]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirCityForecastartResponse> AirCityForecastartAsync(HNHB.WebService.cityAQIService.AirCityForecastartRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityHours", ReplyAction="*")]
        HNHB.WebService.cityAQIService.AirCityHoursResponse AirCityHours(HNHB.WebService.cityAQIService.AirCityHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityHours", ReplyAction="*")]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirCityHoursResponse> AirCityHoursAsync(HNHB.WebService.cityAQIService.AirCityHoursRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirAwsHours", ReplyAction="*")]
        HNHB.WebService.cityAQIService.AirAwsHoursResponse AirAwsHours(HNHB.WebService.cityAQIService.AirAwsHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirAwsHours", ReplyAction="*")]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirAwsHoursResponse> AirAwsHoursAsync(HNHB.WebService.cityAQIService.AirAwsHoursRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HNHB.WebService.cityAQIService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HNHB.WebService.cityAQIService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirStationHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirStationHours", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirStationHoursRequestBody Body;
        
        public AirStationHoursRequest() {
        }
        
        public AirStationHoursRequest(HNHB.WebService.cityAQIService.AirStationHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirStationHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endtime;
        
        public AirStationHoursRequestBody() {
        }
        
        public AirStationHoursRequestBody(string begintime, string endtime) {
            this.begintime = begintime;
            this.endtime = endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirStationHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirStationHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirStationHoursResponseBody Body;
        
        public AirStationHoursResponse() {
        }
        
        public AirStationHoursResponse(HNHB.WebService.cityAQIService.AirStationHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirStationHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirStationHoursResult;
        
        public AirStationHoursResponseBody() {
        }
        
        public AirStationHoursResponseBody(string AirStationHoursResult) {
            this.AirStationHoursResult = AirStationHoursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirWords", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirWordsRequestBody Body;
        
        public AirWordsRequest() {
        }
        
        public AirWordsRequest(HNHB.WebService.cityAQIService.AirWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        public AirWordsRequestBody() {
        }
        
        public AirWordsRequestBody(string begintime) {
            this.begintime = begintime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirWordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirWordsResponseBody Body;
        
        public AirWordsResponse() {
        }
        
        public AirWordsResponse(HNHB.WebService.cityAQIService.AirWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirWordsResult;
        
        public AirWordsResponseBody() {
        }
        
        public AirWordsResponseBody(string AirWordsResult) {
            this.AirWordsResult = AirWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityForecastartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityForecastart", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirCityForecastartRequestBody Body;
        
        public AirCityForecastartRequest() {
        }
        
        public AirCityForecastartRequest(HNHB.WebService.cityAQIService.AirCityForecastartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityForecastartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        public AirCityForecastartRequestBody() {
        }
        
        public AirCityForecastartRequestBody(string begintime) {
            this.begintime = begintime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityForecastartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityForecastartResponse", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirCityForecastartResponseBody Body;
        
        public AirCityForecastartResponse() {
        }
        
        public AirCityForecastartResponse(HNHB.WebService.cityAQIService.AirCityForecastartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityForecastartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirCityForecastartResult;
        
        public AirCityForecastartResponseBody() {
        }
        
        public AirCityForecastartResponseBody(string AirCityForecastartResult) {
            this.AirCityForecastartResult = AirCityForecastartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityHours", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirCityHoursRequestBody Body;
        
        public AirCityHoursRequest() {
        }
        
        public AirCityHoursRequest(HNHB.WebService.cityAQIService.AirCityHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endtime;
        
        public AirCityHoursRequestBody() {
        }
        
        public AirCityHoursRequestBody(string begintime, string endtime) {
            this.begintime = begintime;
            this.endtime = endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirCityHoursResponseBody Body;
        
        public AirCityHoursResponse() {
        }
        
        public AirCityHoursResponse(HNHB.WebService.cityAQIService.AirCityHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirCityHoursResult;
        
        public AirCityHoursResponseBody() {
        }
        
        public AirCityHoursResponseBody(string AirCityHoursResult) {
            this.AirCityHoursResult = AirCityHoursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirAwsHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirAwsHours", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirAwsHoursRequestBody Body;
        
        public AirAwsHoursRequest() {
        }
        
        public AirAwsHoursRequest(HNHB.WebService.cityAQIService.AirAwsHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirAwsHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endtime;
        
        public AirAwsHoursRequestBody() {
        }
        
        public AirAwsHoursRequestBody(string begintime, string endtime) {
            this.begintime = begintime;
            this.endtime = endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirAwsHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirAwsHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public HNHB.WebService.cityAQIService.AirAwsHoursResponseBody Body;
        
        public AirAwsHoursResponse() {
        }
        
        public AirAwsHoursResponse(HNHB.WebService.cityAQIService.AirAwsHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirAwsHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirAwsHoursResult;
        
        public AirAwsHoursResponseBody() {
        }
        
        public AirAwsHoursResponseBody(string AirAwsHoursResult) {
            this.AirAwsHoursResult = AirAwsHoursResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AirWebServiceSoapChannel : HNHB.WebService.cityAQIService.AirWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirWebServiceSoapClient : System.ServiceModel.ClientBase<HNHB.WebService.cityAQIService.AirWebServiceSoap>, HNHB.WebService.cityAQIService.AirWebServiceSoap {
        
        public AirWebServiceSoapClient() {
        }
        
        public AirWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HNHB.WebService.cityAQIService.HelloWorldResponse HNHB.WebService.cityAQIService.AirWebServiceSoap.HelloWorld(HNHB.WebService.cityAQIService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HNHB.WebService.cityAQIService.HelloWorldRequest inValue = new HNHB.WebService.cityAQIService.HelloWorldRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.HelloWorldRequestBody();
            HNHB.WebService.cityAQIService.HelloWorldResponse retVal = ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.HelloWorldResponse> HNHB.WebService.cityAQIService.AirWebServiceSoap.HelloWorldAsync(HNHB.WebService.cityAQIService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.HelloWorldResponse> HelloWorldAsync() {
            HNHB.WebService.cityAQIService.HelloWorldRequest inValue = new HNHB.WebService.cityAQIService.HelloWorldRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.HelloWorldRequestBody();
            return ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HNHB.WebService.cityAQIService.AirStationHoursResponse HNHB.WebService.cityAQIService.AirWebServiceSoap.AirStationHours(HNHB.WebService.cityAQIService.AirStationHoursRequest request) {
            return base.Channel.AirStationHours(request);
        }
        
        public string AirStationHours(string begintime, string endtime) {
            HNHB.WebService.cityAQIService.AirStationHoursRequest inValue = new HNHB.WebService.cityAQIService.AirStationHoursRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirStationHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            HNHB.WebService.cityAQIService.AirStationHoursResponse retVal = ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirStationHours(inValue);
            return retVal.Body.AirStationHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirStationHoursResponse> HNHB.WebService.cityAQIService.AirWebServiceSoap.AirStationHoursAsync(HNHB.WebService.cityAQIService.AirStationHoursRequest request) {
            return base.Channel.AirStationHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirStationHoursResponse> AirStationHoursAsync(string begintime, string endtime) {
            HNHB.WebService.cityAQIService.AirStationHoursRequest inValue = new HNHB.WebService.cityAQIService.AirStationHoursRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirStationHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            return ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirStationHoursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HNHB.WebService.cityAQIService.AirWordsResponse HNHB.WebService.cityAQIService.AirWebServiceSoap.AirWords(HNHB.WebService.cityAQIService.AirWordsRequest request) {
            return base.Channel.AirWords(request);
        }
        
        public string AirWords(string begintime) {
            HNHB.WebService.cityAQIService.AirWordsRequest inValue = new HNHB.WebService.cityAQIService.AirWordsRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirWordsRequestBody();
            inValue.Body.begintime = begintime;
            HNHB.WebService.cityAQIService.AirWordsResponse retVal = ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirWords(inValue);
            return retVal.Body.AirWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirWordsResponse> HNHB.WebService.cityAQIService.AirWebServiceSoap.AirWordsAsync(HNHB.WebService.cityAQIService.AirWordsRequest request) {
            return base.Channel.AirWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirWordsResponse> AirWordsAsync(string begintime) {
            HNHB.WebService.cityAQIService.AirWordsRequest inValue = new HNHB.WebService.cityAQIService.AirWordsRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirWordsRequestBody();
            inValue.Body.begintime = begintime;
            return ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HNHB.WebService.cityAQIService.AirCityForecastartResponse HNHB.WebService.cityAQIService.AirWebServiceSoap.AirCityForecastart(HNHB.WebService.cityAQIService.AirCityForecastartRequest request) {
            return base.Channel.AirCityForecastart(request);
        }
        
        public string AirCityForecastart(string begintime) {
            HNHB.WebService.cityAQIService.AirCityForecastartRequest inValue = new HNHB.WebService.cityAQIService.AirCityForecastartRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirCityForecastartRequestBody();
            inValue.Body.begintime = begintime;
            HNHB.WebService.cityAQIService.AirCityForecastartResponse retVal = ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirCityForecastart(inValue);
            return retVal.Body.AirCityForecastartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirCityForecastartResponse> HNHB.WebService.cityAQIService.AirWebServiceSoap.AirCityForecastartAsync(HNHB.WebService.cityAQIService.AirCityForecastartRequest request) {
            return base.Channel.AirCityForecastartAsync(request);
        }
        
        public System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirCityForecastartResponse> AirCityForecastartAsync(string begintime) {
            HNHB.WebService.cityAQIService.AirCityForecastartRequest inValue = new HNHB.WebService.cityAQIService.AirCityForecastartRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirCityForecastartRequestBody();
            inValue.Body.begintime = begintime;
            return ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirCityForecastartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HNHB.WebService.cityAQIService.AirCityHoursResponse HNHB.WebService.cityAQIService.AirWebServiceSoap.AirCityHours(HNHB.WebService.cityAQIService.AirCityHoursRequest request) {
            return base.Channel.AirCityHours(request);
        }
        
        public string AirCityHours(string begintime, string endtime) {
            HNHB.WebService.cityAQIService.AirCityHoursRequest inValue = new HNHB.WebService.cityAQIService.AirCityHoursRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirCityHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            HNHB.WebService.cityAQIService.AirCityHoursResponse retVal = ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirCityHours(inValue);
            return retVal.Body.AirCityHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirCityHoursResponse> HNHB.WebService.cityAQIService.AirWebServiceSoap.AirCityHoursAsync(HNHB.WebService.cityAQIService.AirCityHoursRequest request) {
            return base.Channel.AirCityHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirCityHoursResponse> AirCityHoursAsync(string begintime, string endtime) {
            HNHB.WebService.cityAQIService.AirCityHoursRequest inValue = new HNHB.WebService.cityAQIService.AirCityHoursRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirCityHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            return ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirCityHoursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HNHB.WebService.cityAQIService.AirAwsHoursResponse HNHB.WebService.cityAQIService.AirWebServiceSoap.AirAwsHours(HNHB.WebService.cityAQIService.AirAwsHoursRequest request) {
            return base.Channel.AirAwsHours(request);
        }
        
        public string AirAwsHours(string begintime, string endtime) {
            HNHB.WebService.cityAQIService.AirAwsHoursRequest inValue = new HNHB.WebService.cityAQIService.AirAwsHoursRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirAwsHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            HNHB.WebService.cityAQIService.AirAwsHoursResponse retVal = ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirAwsHours(inValue);
            return retVal.Body.AirAwsHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirAwsHoursResponse> HNHB.WebService.cityAQIService.AirWebServiceSoap.AirAwsHoursAsync(HNHB.WebService.cityAQIService.AirAwsHoursRequest request) {
            return base.Channel.AirAwsHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<HNHB.WebService.cityAQIService.AirAwsHoursResponse> AirAwsHoursAsync(string begintime, string endtime) {
            HNHB.WebService.cityAQIService.AirAwsHoursRequest inValue = new HNHB.WebService.cityAQIService.AirAwsHoursRequest();
            inValue.Body = new HNHB.WebService.cityAQIService.AirAwsHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            return ((HNHB.WebService.cityAQIService.AirWebServiceSoap)(this)).AirAwsHoursAsync(inValue);
        }
    }
}
