//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNJC.BLL.cityAQIServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cityAQIServices.AirWebServiceSoap")]
    public interface AirWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        JNJC.BLL.cityAQIServices.HelloWorldResponse HelloWorld(JNJC.BLL.cityAQIServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.HelloWorldResponse> HelloWorldAsync(JNJC.BLL.cityAQIServices.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirStationHours", ReplyAction="*")]
        JNJC.BLL.cityAQIServices.AirStationHoursResponse AirStationHours(JNJC.BLL.cityAQIServices.AirStationHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirStationHours", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirStationHoursResponse> AirStationHoursAsync(JNJC.BLL.cityAQIServices.AirStationHoursRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirWords", ReplyAction="*")]
        JNJC.BLL.cityAQIServices.AirWordsResponse AirWords(JNJC.BLL.cityAQIServices.AirWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirWords", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirWordsResponse> AirWordsAsync(JNJC.BLL.cityAQIServices.AirWordsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityForecastart", ReplyAction="*")]
        JNJC.BLL.cityAQIServices.AirCityForecastartResponse AirCityForecastart(JNJC.BLL.cityAQIServices.AirCityForecastartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityForecastart", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirCityForecastartResponse> AirCityForecastartAsync(JNJC.BLL.cityAQIServices.AirCityForecastartRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityHours", ReplyAction="*")]
        JNJC.BLL.cityAQIServices.AirCityHoursResponse AirCityHours(JNJC.BLL.cityAQIServices.AirCityHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirCityHours", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirCityHoursResponse> AirCityHoursAsync(JNJC.BLL.cityAQIServices.AirCityHoursRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 begintime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirAwsHours", ReplyAction="*")]
        JNJC.BLL.cityAQIServices.AirAwsHoursResponse AirAwsHours(JNJC.BLL.cityAQIServices.AirAwsHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AirAwsHours", ReplyAction="*")]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirAwsHoursResponse> AirAwsHoursAsync(JNJC.BLL.cityAQIServices.AirAwsHoursRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(JNJC.BLL.cityAQIServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(JNJC.BLL.cityAQIServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirStationHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirStationHours", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirStationHoursRequestBody Body;
        
        public AirStationHoursRequest() {
        }
        
        public AirStationHoursRequest(JNJC.BLL.cityAQIServices.AirStationHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirStationHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endtime;
        
        public AirStationHoursRequestBody() {
        }
        
        public AirStationHoursRequestBody(string begintime, string endtime) {
            this.begintime = begintime;
            this.endtime = endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirStationHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirStationHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirStationHoursResponseBody Body;
        
        public AirStationHoursResponse() {
        }
        
        public AirStationHoursResponse(JNJC.BLL.cityAQIServices.AirStationHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirStationHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirStationHoursResult;
        
        public AirStationHoursResponseBody() {
        }
        
        public AirStationHoursResponseBody(string AirStationHoursResult) {
            this.AirStationHoursResult = AirStationHoursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirWords", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirWordsRequestBody Body;
        
        public AirWordsRequest() {
        }
        
        public AirWordsRequest(JNJC.BLL.cityAQIServices.AirWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        public AirWordsRequestBody() {
        }
        
        public AirWordsRequestBody(string begintime) {
            this.begintime = begintime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirWordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirWordsResponseBody Body;
        
        public AirWordsResponse() {
        }
        
        public AirWordsResponse(JNJC.BLL.cityAQIServices.AirWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirWordsResult;
        
        public AirWordsResponseBody() {
        }
        
        public AirWordsResponseBody(string AirWordsResult) {
            this.AirWordsResult = AirWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityForecastartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityForecastart", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirCityForecastartRequestBody Body;
        
        public AirCityForecastartRequest() {
        }
        
        public AirCityForecastartRequest(JNJC.BLL.cityAQIServices.AirCityForecastartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityForecastartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        public AirCityForecastartRequestBody() {
        }
        
        public AirCityForecastartRequestBody(string begintime) {
            this.begintime = begintime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityForecastartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityForecastartResponse", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirCityForecastartResponseBody Body;
        
        public AirCityForecastartResponse() {
        }
        
        public AirCityForecastartResponse(JNJC.BLL.cityAQIServices.AirCityForecastartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityForecastartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirCityForecastartResult;
        
        public AirCityForecastartResponseBody() {
        }
        
        public AirCityForecastartResponseBody(string AirCityForecastartResult) {
            this.AirCityForecastartResult = AirCityForecastartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityHours", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirCityHoursRequestBody Body;
        
        public AirCityHoursRequest() {
        }
        
        public AirCityHoursRequest(JNJC.BLL.cityAQIServices.AirCityHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endtime;
        
        public AirCityHoursRequestBody() {
        }
        
        public AirCityHoursRequestBody(string begintime, string endtime) {
            this.begintime = begintime;
            this.endtime = endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirCityHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirCityHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirCityHoursResponseBody Body;
        
        public AirCityHoursResponse() {
        }
        
        public AirCityHoursResponse(JNJC.BLL.cityAQIServices.AirCityHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirCityHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirCityHoursResult;
        
        public AirCityHoursResponseBody() {
        }
        
        public AirCityHoursResponseBody(string AirCityHoursResult) {
            this.AirCityHoursResult = AirCityHoursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirAwsHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirAwsHours", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirAwsHoursRequestBody Body;
        
        public AirAwsHoursRequest() {
        }
        
        public AirAwsHoursRequest(JNJC.BLL.cityAQIServices.AirAwsHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirAwsHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string begintime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endtime;
        
        public AirAwsHoursRequestBody() {
        }
        
        public AirAwsHoursRequestBody(string begintime, string endtime) {
            this.begintime = begintime;
            this.endtime = endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AirAwsHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AirAwsHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public JNJC.BLL.cityAQIServices.AirAwsHoursResponseBody Body;
        
        public AirAwsHoursResponse() {
        }
        
        public AirAwsHoursResponse(JNJC.BLL.cityAQIServices.AirAwsHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AirAwsHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AirAwsHoursResult;
        
        public AirAwsHoursResponseBody() {
        }
        
        public AirAwsHoursResponseBody(string AirAwsHoursResult) {
            this.AirAwsHoursResult = AirAwsHoursResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AirWebServiceSoapChannel : JNJC.BLL.cityAQIServices.AirWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirWebServiceSoapClient : System.ServiceModel.ClientBase<JNJC.BLL.cityAQIServices.AirWebServiceSoap>, JNJC.BLL.cityAQIServices.AirWebServiceSoap {
        
        public AirWebServiceSoapClient() {
        }
        
        public AirWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JNJC.BLL.cityAQIServices.HelloWorldResponse JNJC.BLL.cityAQIServices.AirWebServiceSoap.HelloWorld(JNJC.BLL.cityAQIServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            JNJC.BLL.cityAQIServices.HelloWorldRequest inValue = new JNJC.BLL.cityAQIServices.HelloWorldRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.HelloWorldRequestBody();
            JNJC.BLL.cityAQIServices.HelloWorldResponse retVal = ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.HelloWorldResponse> JNJC.BLL.cityAQIServices.AirWebServiceSoap.HelloWorldAsync(JNJC.BLL.cityAQIServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.HelloWorldResponse> HelloWorldAsync() {
            JNJC.BLL.cityAQIServices.HelloWorldRequest inValue = new JNJC.BLL.cityAQIServices.HelloWorldRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.HelloWorldRequestBody();
            return ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JNJC.BLL.cityAQIServices.AirStationHoursResponse JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirStationHours(JNJC.BLL.cityAQIServices.AirStationHoursRequest request) {
            return base.Channel.AirStationHours(request);
        }
        
        public string AirStationHours(string begintime, string endtime) {
            JNJC.BLL.cityAQIServices.AirStationHoursRequest inValue = new JNJC.BLL.cityAQIServices.AirStationHoursRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirStationHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            JNJC.BLL.cityAQIServices.AirStationHoursResponse retVal = ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirStationHours(inValue);
            return retVal.Body.AirStationHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirStationHoursResponse> JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirStationHoursAsync(JNJC.BLL.cityAQIServices.AirStationHoursRequest request) {
            return base.Channel.AirStationHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirStationHoursResponse> AirStationHoursAsync(string begintime, string endtime) {
            JNJC.BLL.cityAQIServices.AirStationHoursRequest inValue = new JNJC.BLL.cityAQIServices.AirStationHoursRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirStationHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            return ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirStationHoursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JNJC.BLL.cityAQIServices.AirWordsResponse JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirWords(JNJC.BLL.cityAQIServices.AirWordsRequest request) {
            return base.Channel.AirWords(request);
        }
        
        public string AirWords(string begintime) {
            JNJC.BLL.cityAQIServices.AirWordsRequest inValue = new JNJC.BLL.cityAQIServices.AirWordsRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirWordsRequestBody();
            inValue.Body.begintime = begintime;
            JNJC.BLL.cityAQIServices.AirWordsResponse retVal = ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirWords(inValue);
            return retVal.Body.AirWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirWordsResponse> JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirWordsAsync(JNJC.BLL.cityAQIServices.AirWordsRequest request) {
            return base.Channel.AirWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirWordsResponse> AirWordsAsync(string begintime) {
            JNJC.BLL.cityAQIServices.AirWordsRequest inValue = new JNJC.BLL.cityAQIServices.AirWordsRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirWordsRequestBody();
            inValue.Body.begintime = begintime;
            return ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JNJC.BLL.cityAQIServices.AirCityForecastartResponse JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirCityForecastart(JNJC.BLL.cityAQIServices.AirCityForecastartRequest request) {
            return base.Channel.AirCityForecastart(request);
        }
        
        public string AirCityForecastart(string begintime) {
            JNJC.BLL.cityAQIServices.AirCityForecastartRequest inValue = new JNJC.BLL.cityAQIServices.AirCityForecastartRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirCityForecastartRequestBody();
            inValue.Body.begintime = begintime;
            JNJC.BLL.cityAQIServices.AirCityForecastartResponse retVal = ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirCityForecastart(inValue);
            return retVal.Body.AirCityForecastartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirCityForecastartResponse> JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirCityForecastartAsync(JNJC.BLL.cityAQIServices.AirCityForecastartRequest request) {
            return base.Channel.AirCityForecastartAsync(request);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirCityForecastartResponse> AirCityForecastartAsync(string begintime) {
            JNJC.BLL.cityAQIServices.AirCityForecastartRequest inValue = new JNJC.BLL.cityAQIServices.AirCityForecastartRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirCityForecastartRequestBody();
            inValue.Body.begintime = begintime;
            return ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirCityForecastartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JNJC.BLL.cityAQIServices.AirCityHoursResponse JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirCityHours(JNJC.BLL.cityAQIServices.AirCityHoursRequest request) {
            return base.Channel.AirCityHours(request);
        }
        
        public string AirCityHours(string begintime, string endtime) {
            JNJC.BLL.cityAQIServices.AirCityHoursRequest inValue = new JNJC.BLL.cityAQIServices.AirCityHoursRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirCityHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            JNJC.BLL.cityAQIServices.AirCityHoursResponse retVal = ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirCityHours(inValue);
            return retVal.Body.AirCityHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirCityHoursResponse> JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirCityHoursAsync(JNJC.BLL.cityAQIServices.AirCityHoursRequest request) {
            return base.Channel.AirCityHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirCityHoursResponse> AirCityHoursAsync(string begintime, string endtime) {
            JNJC.BLL.cityAQIServices.AirCityHoursRequest inValue = new JNJC.BLL.cityAQIServices.AirCityHoursRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirCityHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            return ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirCityHoursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JNJC.BLL.cityAQIServices.AirAwsHoursResponse JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirAwsHours(JNJC.BLL.cityAQIServices.AirAwsHoursRequest request) {
            return base.Channel.AirAwsHours(request);
        }
        
        public string AirAwsHours(string begintime, string endtime) {
            JNJC.BLL.cityAQIServices.AirAwsHoursRequest inValue = new JNJC.BLL.cityAQIServices.AirAwsHoursRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirAwsHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            JNJC.BLL.cityAQIServices.AirAwsHoursResponse retVal = ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirAwsHours(inValue);
            return retVal.Body.AirAwsHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirAwsHoursResponse> JNJC.BLL.cityAQIServices.AirWebServiceSoap.AirAwsHoursAsync(JNJC.BLL.cityAQIServices.AirAwsHoursRequest request) {
            return base.Channel.AirAwsHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<JNJC.BLL.cityAQIServices.AirAwsHoursResponse> AirAwsHoursAsync(string begintime, string endtime) {
            JNJC.BLL.cityAQIServices.AirAwsHoursRequest inValue = new JNJC.BLL.cityAQIServices.AirAwsHoursRequest();
            inValue.Body = new JNJC.BLL.cityAQIServices.AirAwsHoursRequestBody();
            inValue.Body.begintime = begintime;
            inValue.Body.endtime = endtime;
            return ((JNJC.BLL.cityAQIServices.AirWebServiceSoap)(this)).AirAwsHoursAsync(inValue);
        }
    }
}
